### ISSUE TITLE
Cannot start program after saving file with unicode characters in filename

### ISSUE THREAD

**Issue by gdietz** [bwallace/OpenMeta-analyst-#259]
See email from Agata Złotogórska in the mailing list. Email: 

*I find your software very useful and user-friendly. However, I have a difficult problem with launching it. The problem occurred in two different computers (with Windows 8). In both cases the program started correctly for the first time. Problem occurred when I saved the file. I got error: “errors occurred” redirecting to the log file. My work file was actually saved, but the error occurred with every launch of the program, disabling me to use it. The text from win_prelaunch.exe.log:
„Traceback (most recent call last):
  File "win_prelaunch.py", line 29, in <module>
  File "launch.pyc", line 63, in start
  File "meta_form.pyc", line 122, in __init__
  File "meta_form.pyc", line 270, in populate_open_recent_menu
  File "settings.pyc", line 76, in get_setting
UnicodeEncodeError: 'ascii' codec can't encode character u'\u015b' in position 35: ordinal not in range(128)”
Is there any possibility to fix it?*

**Comment by gdietz** [comment]
It looks like we allow saving the file with unicode characters in the path but when opening it, we try to encode it in to ascii for some reason.

**Comment by gdietz** [comment]
As a workaround while this is fixed, just to make the program launchable again, the user can do the following:
-Run the registry editor: regedit.exe
- Delete the key HKEY_CURRENT_USER\Software\CEBM\OpenMetaAnalyst

**Comment by gdietz** [comment]
if there is an issue trying to load a setting, we just reset all settings to their defaults
